spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxx
    password: xxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true